In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston

In [4]:
boston=load_boston()

In [60]:
df=pd.DataFrame(boston.data,columns=boston.feature_names)
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [61]:
x=boston.data
y=boston.target

In [62]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [63]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [69]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2)
# 80% data for training and 20% data for testing


In [70]:
# applying Liner Regresion
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [71]:
y_pred=reg.predict(x_test)
y_pred

array([13.76450373, 14.15532252, 12.39123593, 20.81398649, 19.35594307,
       25.07142213, 19.26685428, 36.41838955, 29.71583368, 11.89249585,
       18.9118846 , 16.76053853, 25.89726739, 27.16162168, 32.83379838,
       23.54341663, 16.16777106, 21.64324252, 18.48613324, 20.34019477,
       25.29440346, 35.97623588, 11.09735266, 27.5852319 , 30.40023071,
       15.72925113, 23.88353064, 16.66019472, 27.01354775, 29.49605851,
       22.2081783 , 13.02701976, 14.30970332, 24.82890454,  6.67808302,
       15.13311669, 23.86422849, 30.75529942, 26.44357677, 22.03241409,
       19.72173059, 13.62403678, 27.20895022, 19.39992878, 22.98925564,
       25.08674086, 20.88309131, 27.25326877, 22.30918114, 20.47302424,
       36.37134404, 13.08062401, 28.86462845,  9.85497374, 16.78301064,
       22.45813613, 24.95983473, 12.3679725 , 23.79263438,  7.63449889,
       22.39156689, 12.644099  , 20.2663564 , 23.77717   , 25.39170378,
       27.40561337, 36.42282126, 12.73046689, 26.7872484 , 10.60

In [72]:
y_test

array([15.4, 13.1, 13.5, 16.7, 22.9, 23.1, 17.1, 38.7, 23.6,  5.6, 17.1,
       17.5, 29.8, 23.9, 33.2, 24.7, 13.4, 18.7, 17.5, 20.4, 25.3, 35.1,
       15.6, 22.6, 30.1, 17.6, 30.1, 13.8, 23.3, 32.9, 17.4, 14. ,  8.4,
       19.4, 10.4, 18.4, 24.4, 34.7, 24.8, 22.2, 18.6, 14.5, 22.1, 18.4,
       21.2, 25. , 19.6, 27.1, 21.2, 19.3, 33.4, 13.9, 22.8,  9.7, 23.1,
       17.8, 24.3, 13.6, 24.4, 11.8, 20.3, 18.2, 19.5, 22.2, 28.7, 25.2,
       42.3, 18.5, 22.3, 15.2,  7. , 19.6, 26.7, 25. , 44. ,  8.5, 14.6,
       24.4, 27.1, 18.9, 20.6, 21. , 16.2, 23. , 24.5, 50. , 24.2,  8.1,
       27.5, 21.9, 15.7, 34.9, 42.8, 14.6,  8.3, 23.7, 26.5, 19.9, 26.6,
       17.9, 23.3, 23.8])

In [74]:
# mean square error
from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred,y_test)

20.037388539019354